# travis automation/build script for cttp
sudo: required
language: c

compiler:
  - gcc

install:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-6
  - sudo apt-get install -y -qq valgrind
  - export CC=gcc-6
  - export NM=gcc-nm-6
  - export RANLIB=gcc-ranlib-6
  - wget https://cmocka.org/files/1.1/cmocka-1.1.1.tar.xz
  - tar -xvf cmocka-1.1.1.tar.xz
  - cd cmocka-1.1.1
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
  - make
  - sudo make install
  - cd ${TRAVIS_BUILD_DIR}
  
script:
  - cmake . && make
  - ctest
