# travis automation/build script for cttp
language: c

compiler:
  - gcc-4.8

addons:
  apt:
    sources:
      - george-edison55/cmake-3.x
    packages:
      - cmake-data
      - cmake
      - cmocka
      - libcmocka-dev

# TODO: throw in testing as well once the testing framework is set up
script:
  - cmake . && make
